Added language support for DE, EN and FR
brettdottech/info-orbs pull request #82
Opened 2024-10-28 12:37 UTC by HugoBalder

2024-10-29 06:51 UTC, HugoBalder commented
Second try with the pull request, now using the dev branch, which is far better :)

2024-10-29 08:00 UTC, flattermann commented
That looks much better! :-)

One small issue: I think you accidently overwrote the already merged changes in config.h.template.
(Some fixes for spelling errors and the new define for WIDGET_CYCLE_DELAY.)

https://github.com/brettdottech/info-orbs/pull/82/files

If you fix this in your dev branch, this PR will be updated automatically.

2024-10-29 09:07 UTC, HugoBalder commented
Hi flattermann, i fixed the config.h.template and i should be correct now :)

2024-10-29 21:38 UTC, ericthelin requested changes

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> +            model.setUhrzeit(doc["currentConditions"]["datetime"].as<String>());
what is `Uhrzeit` is that german? Please use english for code.

2024-10-29 21:38 UTC, ericthelin commented on firmware/lib/globalTime/globalTime.cpp
> +        m_monthName = LOC_MONTH[m_month-1];
Please remove both the comment about what you are changing and the old version. That is what version control is for.

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> +// dosent round deg, just removes all text after the decimil, should prob be fixed
Please remove this as it introduces incorrect spelling.

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> +    // given the small width of the screens this will porbablly be needed to this project again so making sure to outline it
these are complete sentences so the capitalization is correct

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> +    display.setTextSize(3);
extra space. extra comment. non-english words

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> +//        String weekUpdate = dayStr(weekday(m_time->getUnixEpoch() + (86400 * (i + 1))));
extra comments.

2024-10-29 21:38 UTC, ericthelin commented on firmware/src/widgets/weatherWidget.cpp
> -}
This was just added. Do not remove it. Please add the trailing new line back.

2024-10-29 21:44 UTC, ericthelin reviewed
I like the concepts but it still needs some changes. And preferably narrowed down to just the language support.

2024-10-29 21:44 UTC, ericthelin commented on firmware/lib/config/config.h.template
> +#define WIFI_PASS "WIFIPASS" // wifi password
I am not sure we need the capitalization changes but if we do make them they should be in a separate PR. As they do not relate to adding german and french support.

2024-10-29 21:44 UTC, ericthelin commented on firmware/lib/config/config.h.template
> +#define FORMAT_24_HOUR false // toggle 24 hour clock vs 12 hour clock, chnage between true/false
"change" is correct.

2024-10-29 21:44 UTC, ericthelin commented on firmware/lib/config/config.h.template
> +#define LOC_DE // Defined if Monthnames and Weekdays should be in German
German should not be the default.

2024-10-29 21:44 UTC, ericthelin commented on firmware/lib/config/config.h.template
> +#endif
it would probably be better to have english be an else so if you don't specify another language you get english

2024-10-30 07:31 UTC, HugoBalder commented
Hi ericthlin, i made all your requested changes and uploaded the files to my dev branch. Default for language is now English.

2024-11-02 07:11 UTC, merged